/* AUTO-GENERATED by scripts/install-character-assets.mjs — do not edit */
export const CHARACTER_RUNTIME_MANIFEST_URL = '/assets/characters/manifests/character_runtime_manifest.json' as const;
export const CHARACTER_DEFAULT_APPEARANCE = {
  "version": 1,
  "baseId": "base_skin_light",
  "hairId": "hair_crew_cut_01",
  "facialHairId": null,
  "headwearId": null,
  "outfitId": "outfit_market_tunic",
  "pantsId": "pants_dark_jeans_01",
  "shoesId": null,
  "accessoryIds": []
} as const;
export const CHARACTER_ATLAS_KEYS = [
  "char-atlas-atlas_accessories",
  "char-atlas-atlas_facial-hair",
  "char-atlas-atlas_hair",
  "char-atlas-atlas_headwear_1",
  "char-atlas-atlas_headwear_2",
  "char-atlas-atlas_npcs_1",
  "char-atlas-atlas_npcs_2",
  "char-atlas-atlas_pants",
  "char-atlas-atlas_shoes"
] as const;
export const CHARACTER_BASE_TEXTURES = [
  {
    "id": "base_skin_fair",
    "textureKey": "char-base-base_skin_fair",
    "url": "/assets/characters/bases/base_skin_fair.png"
  },
  {
    "id": "base_skin_light",
    "textureKey": "char-base-base_skin_light",
    "url": "/assets/characters/bases/base_skin_light.png"
  },
  {
    "id": "base_skin_medium",
    "textureKey": "char-base-base_skin_medium",
    "url": "/assets/characters/bases/base_skin_medium.png"
  },
  {
    "id": "base_skin_tan",
    "textureKey": "char-base-base_skin_tan",
    "url": "/assets/characters/bases/base_skin_tan.png"
  },
  {
    "id": "base_skin_deep",
    "textureKey": "char-base-base_skin_deep",
    "url": "/assets/characters/bases/base_skin_deep.png"
  },
  {
    "id": "base_skin_dark",
    "textureKey": "char-base-base_skin_dark",
    "url": "/assets/characters/bases/base_skin_dark.png"
  }
] as const;
