-- RugTown Phase 10L: characters, world events, tournaments and guilds.
-- Additive on 10G–10K. All rewards are in-game only; no SOL/SPL.
BEGIN;

-- ============================================================================
-- 1 Characters
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.character_cosmetic_definitions (
  id text PRIMARY KEY CHECK (id ~ '^[a-z0-9_:-]{3,80}$'),
  name text NOT NULL, slot text NOT NULL CHECK (slot IN ('base','hair','outfit','hat','glasses','badge')),
  rarity text NOT NULL DEFAULT 'common', status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft','active','retired')), metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.player_character_cosmetics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), player_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  cosmetic_id text NOT NULL REFERENCES public.character_cosmetic_definitions(id), source_type text NOT NULL DEFAULT 'default',
  source_id text, granted_by uuid REFERENCES public.profiles(id), granted_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz, revoke_reason text, UNIQUE(player_id, cosmetic_id)
);
CREATE TABLE IF NOT EXISTS public.player_character_loadouts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), player_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT 'Default' CHECK (char_length(trim(name)) BETWEEN 1 AND 32),
  slots jsonb NOT NULL DEFAULT '{}'::jsonb, is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_character_active_loadout ON public.player_character_loadouts(player_id) WHERE is_active;
CREATE TABLE IF NOT EXISTS public.character_loadout_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), loadout_id uuid REFERENCES public.player_character_loadouts(id) ON DELETE SET NULL,
  player_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, actor_id uuid REFERENCES public.profiles(id),
  action_type text NOT NULL, before_slots jsonb, after_slots jsonb, reason text, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.character_cosmetic_entitlements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), player_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  cosmetic_id text NOT NULL REFERENCES public.character_cosmetic_definitions(id), source_type text NOT NULL,
  source_id text, status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','revoked','expired')),
  granted_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz, UNIQUE(player_id, cosmetic_id, source_type, source_id)
);
ALTER TABLE public.character_cosmetic_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_character_cosmetics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_character_loadouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.character_loadout_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.character_cosmetic_entitlements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "character cosmetics owner read" ON public.player_character_cosmetics;
CREATE POLICY "character cosmetics owner read" ON public.player_character_cosmetics FOR SELECT USING (player_id=auth.uid());
DROP POLICY IF EXISTS "character loadouts owner read" ON public.player_character_loadouts;
CREATE POLICY "character loadouts owner read" ON public.player_character_loadouts FOR SELECT USING (player_id=auth.uid());
DROP POLICY IF EXISTS "character history owner read" ON public.character_loadout_history;
CREATE POLICY "character history owner read" ON public.character_loadout_history FOR SELECT USING (player_id=auth.uid());
DROP POLICY IF EXISTS "cosmetic catalog public read" ON public.character_cosmetic_definitions;
CREATE POLICY "cosmetic catalog public read" ON public.character_cosmetic_definitions FOR SELECT USING (status='active');

CREATE OR REPLACE FUNCTION public.rt_ensure_default_character_cosmetics(p_player uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  INSERT INTO public.player_character_cosmetics(player_id,cosmetic_id,source_type)
  SELECT p_player,id,'default' FROM public.character_cosmetic_definitions
  WHERE id IN ('base_default','hair_short','hair_long','outfit_starter_dark','outfit_market_apron','hat_beanie','glasses_round')
    AND status='active'
  ON CONFLICT(player_id,cosmetic_id) DO NOTHING;
  IF NOT EXISTS (
    SELECT 1 FROM public.player_character_loadouts WHERE player_id = p_player AND is_active
  ) THEN
    INSERT INTO public.player_character_loadouts(player_id,name,slots)
    VALUES(p_player,'Default','{"base":"base_default","hair":"hair_short","outfit":"outfit_starter_dark"}');
  END IF;
END $$;
CREATE OR REPLACE FUNCTION public.get_my_character_cosmetics()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE uid uuid:=auth.uid(); BEGIN IF uid IS NULL THEN RAISE EXCEPTION 'authentication required'; END IF;
 PERFORM public.rt_ensure_default_character_cosmetics(uid);
 RETURN jsonb_build_object('cosmetics',coalesce((SELECT jsonb_agg(jsonb_build_object('id',d.id,'name',d.name,'slot',d.slot,'rarity',d.rarity,'grantedAt',c.granted_at) ORDER BY d.slot,d.id) FROM public.player_character_cosmetics c JOIN public.character_cosmetic_definitions d ON d.id=c.cosmetic_id WHERE c.player_id=uid AND c.revoked_at IS NULL),'[]'::jsonb)); END $$;
CREATE OR REPLACE FUNCTION public.get_my_character_loadout()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE uid uuid:=auth.uid(); BEGIN IF uid IS NULL THEN RAISE EXCEPTION 'authentication required'; END IF; PERFORM public.rt_ensure_default_character_cosmetics(uid);
 RETURN coalesce((SELECT to_jsonb(l) FROM public.player_character_loadouts l WHERE l.player_id=uid AND l.is_active),'null'::jsonb); END $$;
CREATE OR REPLACE FUNCTION public.update_character_loadout(p_slots jsonb, p_name text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE uid uuid:=auth.uid(); l public.player_character_loadouts; key text; cid text;
BEGIN
 IF uid IS NULL OR public.rt_social_restricted(uid) THEN RAISE EXCEPTION 'character update unavailable'; END IF;
 IF jsonb_typeof(p_slots)<>'object' OR EXISTS(SELECT 1 FROM jsonb_each_text(p_slots) x WHERE x.key NOT IN ('base','hair','outfit','hat','glasses','badge') OR x.value !~ '^[a-z0-9_:-]{3,80}$') THEN RAISE EXCEPTION 'invalid cosmetic ids'; END IF;
 PERFORM public.rt_ensure_default_character_cosmetics(uid);
 FOR key,cid IN SELECT key,value FROM jsonb_each_text(p_slots) LOOP
   IF NOT EXISTS(SELECT 1 FROM public.player_character_cosmetics c JOIN public.character_cosmetic_definitions d ON d.id=c.cosmetic_id WHERE c.player_id=uid AND c.cosmetic_id=cid AND c.revoked_at IS NULL AND d.slot=key AND d.status='active') THEN RAISE EXCEPTION 'cosmetic not owned or invalid slot'; END IF;
 END LOOP;
 SELECT * INTO l FROM public.player_character_loadouts WHERE player_id=uid AND is_active FOR UPDATE;
 UPDATE public.player_character_loadouts SET slots=p_slots,name=coalesce(nullif(left(trim(p_name),32),''),name),updated_at=now() WHERE id=l.id;
 INSERT INTO public.character_loadout_history(loadout_id,player_id,actor_id,action_type,before_slots,after_slots) VALUES(l.id,uid,uid,'updated',l.slots,p_slots);
 RETURN jsonb_build_object('ok',true,'loadoutId',l.id); END $$;
CREATE OR REPLACE FUNCTION public.get_public_character_loadout(p_player_id uuid)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT coalesce((SELECT jsonb_build_object('playerId',l.player_id,'slots',l.slots,'updatedAt',l.updated_at) FROM public.player_character_loadouts l WHERE l.player_id=p_player_id AND l.is_active),'null'::jsonb); $$;
CREATE OR REPLACE FUNCTION public.grant_character_cosmetic(p_player uuid,p_cosmetic text,p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.character_cosmetic_definitions WHERE id=p_cosmetic) THEN RAISE EXCEPTION 'unknown cosmetic'; END IF;
 INSERT INTO public.player_character_cosmetics(player_id,cosmetic_id,source_type,source_id,granted_by) VALUES(p_player,p_cosmetic,'operator',left(trim(p_reason),200),auth.uid()) ON CONFLICT(player_id,cosmetic_id) DO UPDATE SET revoked_at=NULL,revoke_reason=NULL,granted_at=now(),granted_by=auth.uid();
 INSERT INTO public.character_loadout_history(player_id,actor_id,action_type,reason) VALUES(p_player,auth.uid(),'cosmetic_granted',left(trim(p_reason),200)); RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.revoke_character_cosmetic(p_player uuid,p_cosmetic text,p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF;
 UPDATE public.player_character_cosmetics SET revoked_at=now(),revoke_reason=left(trim(p_reason),200) WHERE player_id=p_player AND cosmetic_id=p_cosmetic;
 INSERT INTO public.character_loadout_history(player_id,actor_id,action_type,reason) VALUES(p_player,auth.uid(),'cosmetic_revoked',left(trim(p_reason),200)); RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.reconcile_character_loadout(p_player uuid DEFAULT auth.uid())
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE l public.player_character_loadouts; clean jsonb:='{}'::jsonb; k text; v text; BEGIN
 IF p_player<>auth.uid() AND NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'permission denied'; END IF; PERFORM public.rt_ensure_default_character_cosmetics(p_player);
 SELECT * INTO l FROM public.player_character_loadouts WHERE player_id=p_player AND is_active FOR UPDATE;
 FOR k,v IN SELECT key,value FROM jsonb_each_text(l.slots) LOOP IF EXISTS(SELECT 1 FROM public.player_character_cosmetics WHERE player_id=p_player AND cosmetic_id=v AND revoked_at IS NULL) THEN clean:=clean||jsonb_build_object(k,v); END IF; END LOOP;
 UPDATE public.player_character_loadouts SET slots=clean,updated_at=now() WHERE id=l.id; RETURN jsonb_build_object('ok',true,'slots',clean); END $$;

-- ============================================================================
-- 2 World events
-- ============================================================================
DO $$ BEGIN CREATE TYPE public.world_event_status AS ENUM ('draft','scheduled','registration_open','active','evaluating','completed','cancelled','archived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS public.world_event_definitions(id text PRIMARY KEY CHECK(id~'^[a-z0-9-]{3,80}$'),name text NOT NULL,description text NOT NULL DEFAULT '',status public.world_event_status NOT NULL DEFAULT 'draft',is_test boolean NOT NULL DEFAULT true,reward_xp integer NOT NULL DEFAULT 0 CHECK(reward_xp>=0),reward_rep integer NOT NULL DEFAULT 0 CHECK(reward_rep>=0),metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.world_event_schedules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),definition_id text NOT NULL REFERENCES public.world_event_definitions(id),starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,registration_opens_at timestamptz NOT NULL DEFAULT now(),status public.world_event_status NOT NULL DEFAULT 'scheduled',UNIQUE(definition_id,starts_at),CHECK(ends_at>starts_at));
CREATE TABLE IF NOT EXISTS public.world_event_instances(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),definition_id text NOT NULL REFERENCES public.world_event_definitions(id),schedule_id uuid REFERENCES public.world_event_schedules(id),status public.world_event_status NOT NULL DEFAULT 'scheduled',starts_at timestamptz,ends_at timestamptz,evaluated_at timestamptz,created_by uuid REFERENCES public.profiles(id),metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS public.world_event_objectives(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid NOT NULL REFERENCES public.world_event_instances(id) ON DELETE CASCADE,objective_key text NOT NULL,goal integer NOT NULL CHECK(goal>0),progress integer NOT NULL DEFAULT 0,UNIQUE(instance_id,objective_key));
CREATE TABLE IF NOT EXISTS public.world_event_participants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid NOT NULL REFERENCES public.world_event_instances(id) ON DELETE CASCADE,player_id uuid NOT NULL REFERENCES public.profiles(id),status text NOT NULL DEFAULT 'registered' CHECK(status IN('registered','withdrawn','eligible','ineligible')),registered_at timestamptz NOT NULL DEFAULT now(),withdrawn_at timestamptz,UNIQUE(instance_id,player_id));
CREATE TABLE IF NOT EXISTS public.world_event_contributions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid NOT NULL REFERENCES public.world_event_instances(id) ON DELETE CASCADE,player_id uuid NOT NULL REFERENCES public.profiles(id),action_receipt_id uuid REFERENCES public.gameplay_action_receipts(id),objective_key text NOT NULL,value integer NOT NULL DEFAULT 1 CHECK(value>0),evidence_hash text NOT NULL,status text NOT NULL DEFAULT 'accepted',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(instance_id,evidence_hash),UNIQUE(instance_id,action_receipt_id));
CREATE TABLE IF NOT EXISTS public.world_event_reward_allocations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid NOT NULL REFERENCES public.world_event_instances(id) ON DELETE CASCADE,player_id uuid NOT NULL REFERENCES public.profiles(id),asset_type text NOT NULL CHECK(asset_type IN('XP','REP','RUG_POINTS')),amount integer NOT NULL CHECK(amount>=0),status text NOT NULL DEFAULT 'claimable',idempotency_key text NOT NULL UNIQUE,UNIQUE(instance_id,player_id,asset_type));
CREATE TABLE IF NOT EXISTS public.world_event_reward_claims(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),allocation_id uuid NOT NULL UNIQUE REFERENCES public.world_event_reward_allocations(id),player_id uuid NOT NULL REFERENCES public.profiles(id),reward_ledger_id uuid,claimed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.world_event_announcements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid REFERENCES public.world_event_instances(id) ON DELETE CASCADE,title text NOT NULL,body text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.world_event_activity_log(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid REFERENCES public.world_event_instances(id),actor_id uuid,event_type text NOT NULL,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.world_event_analytics_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_type text NOT NULL,instance_id uuid,player_id uuid,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.world_event_operational_alerts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text NOT NULL,status text NOT NULL DEFAULT 'open',message_safe text NOT NULL DEFAULT '',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.world_event_job_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_name text NOT NULL,status text NOT NULL DEFAULT 'running',started_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
ALTER TABLE public.world_event_definitions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_schedules ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_instances ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_objectives ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_participants ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_contributions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_reward_allocations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_reward_claims ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_announcements ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_activity_log ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_analytics_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_operational_alerts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.world_event_job_runs ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.transition_world_event_state(p_instance uuid,p_state text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF; IF p_state NOT IN ('scheduled','registration_open','active','evaluating','completed','cancelled','archived') THEN RAISE EXCEPTION 'invalid state'; END IF; UPDATE public.world_event_instances SET status=p_state::public.world_event_status,evaluated_at=CASE WHEN p_state='evaluating' THEN now() ELSE evaluated_at END WHERE id=p_instance; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.schedule_world_event(p_definition text,p_starts timestamptz,p_ends timestamptz)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE sid uuid; iid uuid; BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF; IF p_ends<=p_starts THEN RAISE EXCEPTION 'invalid schedule'; END IF; INSERT INTO public.world_event_schedules(definition_id,starts_at,ends_at,registration_opens_at) VALUES(p_definition,p_starts,p_ends,p_starts-interval '1 day') RETURNING id INTO sid; INSERT INTO public.world_event_instances(definition_id,schedule_id,starts_at,ends_at,status,created_by) VALUES(p_definition,sid,p_starts,p_ends,'scheduled',auth.uid()) RETURNING id INTO iid; RETURN jsonb_build_object('ok',true,'instanceId',iid); END $$;
CREATE OR REPLACE FUNCTION public.register_for_world_event(p_instance uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE uid uuid:=auth.uid(); BEGIN IF uid IS NULL OR public.rt_social_restricted(uid) THEN RAISE EXCEPTION 'registration unavailable'; END IF; IF NOT EXISTS(SELECT 1 FROM public.world_event_instances WHERE id=p_instance AND status IN('registration_open','active')) THEN RAISE EXCEPTION 'event unavailable'; END IF; INSERT INTO public.world_event_participants(instance_id,player_id) VALUES(p_instance,uid) ON CONFLICT(instance_id,player_id) DO UPDATE SET status='registered',withdrawn_at=NULL; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.withdraw_from_world_event(p_instance uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN UPDATE public.world_event_participants SET status='withdrawn',withdrawn_at=now() WHERE instance_id=p_instance AND player_id=auth.uid() AND status='registered'; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.get_my_world_event_registration(p_instance uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT coalesce((SELECT to_jsonb(p) FROM public.world_event_participants p WHERE p.instance_id=p_instance AND p.player_id=auth.uid()),'null'::jsonb); $$;
CREATE OR REPLACE FUNCTION public.record_world_event_contribution(p_instance uuid,p_objective text,p_receipt uuid,p_evidence text,p_value integer DEFAULT 1) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE uid uuid:=auth.uid(); BEGIN IF uid IS NULL OR p_value<1 OR p_value>100 OR nullif(trim(p_evidence),'') IS NULL THEN RAISE EXCEPTION 'invalid contribution'; END IF; IF NOT EXISTS(SELECT 1 FROM public.world_event_participants WHERE instance_id=p_instance AND player_id=uid AND status='registered') OR NOT EXISTS(SELECT 1 FROM public.world_event_instances WHERE id=p_instance AND status='active') THEN RAISE EXCEPTION 'not eligible'; END IF; IF p_receipt IS NULL OR NOT EXISTS(SELECT 1 FROM public.gameplay_action_receipts WHERE id=p_receipt AND player_id=uid AND status='accepted') THEN RAISE EXCEPTION 'trusted receipt required'; END IF; INSERT INTO public.world_event_contributions(instance_id,player_id,action_receipt_id,objective_key,evidence_hash,value) VALUES(p_instance,uid,p_receipt,trim(p_objective),trim(p_evidence),p_value); UPDATE public.world_event_objectives SET progress=least(goal,progress+p_value) WHERE instance_id=p_instance AND objective_key=p_objective; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.evaluate_world_event_instance(p_instance uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE i public.world_event_instances; d public.world_event_definitions; BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF; SELECT * INTO i FROM public.world_event_instances WHERE id=p_instance FOR UPDATE; SELECT * INTO d FROM public.world_event_definitions WHERE id=i.definition_id; INSERT INTO public.world_event_reward_allocations(instance_id,player_id,asset_type,amount,idempotency_key) SELECT i.id,p.player_id,'XP',d.reward_xp,'event:'||i.id||':'||p.player_id||':xp' FROM public.world_event_participants p WHERE p.instance_id=i.id AND p.status='registered' AND d.reward_xp>0 ON CONFLICT DO NOTHING; INSERT INTO public.world_event_reward_allocations(instance_id,player_id,asset_type,amount,idempotency_key) SELECT i.id,p.player_id,'REP',d.reward_rep,'event:'||i.id||':'||p.player_id||':rep' FROM public.world_event_participants p WHERE p.instance_id=i.id AND p.status='registered' AND d.reward_rep>0 ON CONFLICT DO NOTHING; UPDATE public.world_event_instances SET status='completed',evaluated_at=now() WHERE id=i.id; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.get_active_world_events() RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT coalesce(jsonb_agg(to_jsonb(i) ORDER BY i.starts_at),'[]'::jsonb) FROM public.world_event_instances i WHERE i.status IN('registration_open','active'); $$;
CREATE OR REPLACE FUNCTION public.claim_world_event_reward(p_allocation uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE a public.world_event_reward_allocations; BEGIN SELECT * INTO a FROM public.world_event_reward_allocations WHERE id=p_allocation FOR UPDATE; IF a.player_id IS DISTINCT FROM auth.uid() OR a.status<>'claimable' THEN RAISE EXCEPTION 'reward unavailable'; END IF; PERFORM public.rt_set_mutation_flag(); INSERT INTO public.reward_ledger(player_id,reward_type,amount,reason,source_type,source_id,idempotency_key) VALUES(a.player_id,a.asset_type,a.amount,'World event reward','world_event',a.instance_id::text,'claim:'||a.id::text) ON CONFLICT(player_id,idempotency_key) DO NOTHING; UPDATE public.world_event_reward_allocations SET status='claimed' WHERE id=a.id; INSERT INTO public.world_event_reward_claims(allocation_id,player_id) VALUES(a.id,a.player_id) ON CONFLICT DO NOTHING; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.run_world_event_maintenance() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF; UPDATE public.world_event_instances SET status='registration_open' WHERE status='scheduled' AND starts_at-now()<=interval '1 day'; UPDATE public.world_event_instances SET status='active' WHERE status='registration_open' AND starts_at<=now(); UPDATE public.world_event_instances SET status='evaluating' WHERE status='active' AND ends_at<=now(); RETURN jsonb_build_object('ok',true); END $$;

-- ============================================================================
-- 3 Tournaments
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.tournament_definitions(id text PRIMARY KEY,name text NOT NULL,status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','active','archived')),is_test boolean NOT NULL DEFAULT true,rules jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.tournament_instances(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),definition_id text NOT NULL REFERENCES public.tournament_definitions(id),status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','registration_open','active','finalized','cancelled')),starts_at timestamptz,ends_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.tournament_registrations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid NOT NULL REFERENCES public.tournament_instances(id) ON DELETE CASCADE,player_id uuid NOT NULL REFERENCES public.profiles(id),status text NOT NULL DEFAULT 'registered',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(instance_id,player_id));
CREATE TABLE IF NOT EXISTS public.tournament_rounds(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid NOT NULL REFERENCES public.tournament_instances(id) ON DELETE CASCADE,round_number integer NOT NULL,status text NOT NULL DEFAULT 'pending',UNIQUE(instance_id,round_number));
CREATE TABLE IF NOT EXISTS public.tournament_scores(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),round_id uuid NOT NULL REFERENCES public.tournament_rounds(id) ON DELETE CASCADE,player_id uuid NOT NULL REFERENCES public.profiles(id),action_receipt_id uuid REFERENCES public.gameplay_action_receipts(id),score integer NOT NULL CHECK(score>=0),status text NOT NULL DEFAULT 'accepted',UNIQUE(round_id,player_id),UNIQUE(action_receipt_id));
CREATE TABLE IF NOT EXISTS public.tournament_standings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid NOT NULL REFERENCES public.tournament_instances(id) ON DELETE CASCADE,player_id uuid NOT NULL REFERENCES public.profiles(id),score integer NOT NULL DEFAULT 0,rank integer,updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(instance_id,player_id));
CREATE TABLE IF NOT EXISTS public.tournament_reward_allocations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid NOT NULL REFERENCES public.tournament_instances(id),player_id uuid NOT NULL REFERENCES public.profiles(id),asset_type text NOT NULL CHECK(asset_type IN('XP','REP','RUG_POINTS','COSMETIC')),amount integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'claimable',idempotency_key text NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS public.tournament_disputes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid NOT NULL REFERENCES public.tournament_instances(id),player_id uuid NOT NULL REFERENCES public.profiles(id),reason text NOT NULL,status text NOT NULL DEFAULT 'open',created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.tournament_definitions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.tournament_instances ENABLE ROW LEVEL SECURITY; ALTER TABLE public.tournament_registrations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.tournament_rounds ENABLE ROW LEVEL SECURITY; ALTER TABLE public.tournament_scores ENABLE ROW LEVEL SECURITY; ALTER TABLE public.tournament_standings ENABLE ROW LEVEL SECURITY; ALTER TABLE public.tournament_reward_allocations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.tournament_disputes ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.register_for_tournament(p_instance uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.uid() IS NULL OR public.rt_social_restricted(auth.uid()) OR NOT public.rt_check_rate_limit(auth.uid(),'tournament_registration',10,3600) THEN RAISE EXCEPTION 'registration unavailable'; END IF; IF NOT EXISTS(SELECT 1 FROM public.tournament_instances WHERE id=p_instance AND status='registration_open') THEN RAISE EXCEPTION 'tournament unavailable'; END IF; INSERT INTO public.tournament_registrations(instance_id,player_id) VALUES(p_instance,auth.uid()) ON CONFLICT DO NOTHING; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.submit_tournament_score(p_round uuid,p_receipt uuid,p_score integer) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE uid uuid:=auth.uid(); iid uuid; BEGIN IF uid IS NULL OR p_score<0 THEN RAISE EXCEPTION 'invalid score'; END IF; SELECT r.instance_id INTO iid FROM public.tournament_rounds r JOIN public.tournament_instances i ON i.id=r.instance_id WHERE r.id=p_round AND r.status='active' AND i.status='active'; IF iid IS NULL OR NOT EXISTS(SELECT 1 FROM public.tournament_registrations WHERE instance_id=iid AND player_id=uid AND status='registered') OR NOT EXISTS(SELECT 1 FROM public.gameplay_action_receipts WHERE id=p_receipt AND player_id=uid AND status='accepted') THEN RAISE EXCEPTION 'trusted score unavailable'; END IF; INSERT INTO public.tournament_scores(round_id,player_id,action_receipt_id,score) VALUES(p_round,uid,p_receipt,p_score) ON CONFLICT(round_id,player_id) DO UPDATE SET score=EXCLUDED.score,action_receipt_id=EXCLUDED.action_receipt_id; INSERT INTO public.tournament_standings(instance_id,player_id,score) VALUES(iid,uid,p_score) ON CONFLICT(instance_id,player_id) DO UPDATE SET score=(SELECT coalesce(sum(s.score),0) FROM public.tournament_scores s JOIN public.tournament_rounds r ON r.id=s.round_id WHERE r.instance_id=iid AND s.player_id=uid),updated_at=now(); RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.get_tournament_standings(p_instance uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN RETURN jsonb_build_object('standings',coalesce((SELECT jsonb_agg(to_jsonb(s) ORDER BY s.rank NULLS LAST,s.score DESC) FROM public.tournament_standings s WHERE s.instance_id=p_instance),'[]'::jsonb)); END $$;
CREATE OR REPLACE FUNCTION public.finalize_tournament_results(p_instance uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF; WITH ranked AS (SELECT id,rank() OVER(ORDER BY score DESC,updated_at) r FROM public.tournament_standings WHERE instance_id=p_instance) UPDATE public.tournament_standings s SET rank=ranked.r FROM ranked WHERE s.id=ranked.id; UPDATE public.tournament_instances SET status='finalized' WHERE id=p_instance; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.file_tournament_dispute(p_instance uuid,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.uid() IS NULL OR char_length(trim(coalesce(p_reason,'')))<3 THEN RAISE EXCEPTION 'invalid dispute'; END IF; INSERT INTO public.tournament_disputes(instance_id,player_id,reason) VALUES(p_instance,auth.uid(),left(trim(p_reason),1000)); RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.claim_tournament_reward(p_allocation uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE a public.tournament_reward_allocations; BEGIN SELECT * INTO a FROM public.tournament_reward_allocations WHERE id=p_allocation FOR UPDATE; IF a.player_id IS DISTINCT FROM auth.uid() OR a.status<>'claimable' OR a.asset_type='COSMETIC' THEN RAISE EXCEPTION 'reward unavailable'; END IF; PERFORM public.rt_set_mutation_flag(); INSERT INTO public.reward_ledger(player_id,reward_type,amount,reason,source_type,source_id,idempotency_key) VALUES(a.player_id,a.asset_type,a.amount,'Tournament reward','tournament',a.instance_id::text,'claim:'||a.id::text) ON CONFLICT DO NOTHING; UPDATE public.tournament_reward_allocations SET status='claimed' WHERE id=a.id; RETURN jsonb_build_object('ok',true); END $$;

-- ============================================================================
-- 4 Guilds
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.guilds(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,normalized_name text NOT NULL UNIQUE,tag text NOT NULL UNIQUE,leader_id uuid NOT NULL REFERENCES public.profiles(id),join_policy text NOT NULL DEFAULT 'invite_only' CHECK(join_policy IN('invite_only','request')),max_members integer NOT NULL DEFAULT 20 CHECK(max_members BETWEEN 2 AND 20),discoverable boolean NOT NULL DEFAULT false,status text NOT NULL DEFAULT 'active' CHECK(status IN('active','disbanded')),description text,created_at timestamptz NOT NULL DEFAULT now(),disbanded_at timestamptz);
CREATE TABLE IF NOT EXISTS public.guild_members(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,player_id uuid NOT NULL REFERENCES public.profiles(id),role text NOT NULL DEFAULT 'member' CHECK(role IN('leader','officer','member')),status text NOT NULL DEFAULT 'active' CHECK(status IN('active','left','removed')),joined_at timestamptz NOT NULL DEFAULT now(),left_at timestamptz,UNIQUE(guild_id,player_id));
CREATE UNIQUE INDEX IF NOT EXISTS uq_guild_one_active_membership ON public.guild_members(player_id) WHERE status='active' AND left_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_guild_one_leader ON public.guild_members(guild_id) WHERE role='leader' AND status='active' AND left_at IS NULL;
CREATE TABLE IF NOT EXISTS public.guild_invitations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,sender_id uuid NOT NULL REFERENCES public.profiles(id),recipient_id uuid NOT NULL REFERENCES public.profiles(id),status text NOT NULL DEFAULT 'pending',expires_at timestamptz NOT NULL DEFAULT now()+interval '24 hours',UNIQUE(guild_id,recipient_id,status));
CREATE TABLE IF NOT EXISTS public.guild_join_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,player_id uuid NOT NULL REFERENCES public.profiles(id),status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(guild_id,player_id,status));
CREATE TABLE IF NOT EXISTS public.guild_chat_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,sender_id uuid NOT NULL REFERENCES public.profiles(id),client_message_id text NOT NULL,body text NOT NULL,safe_body text,status text NOT NULL DEFAULT 'sent',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(guild_id,sender_id,client_message_id));
CREATE TABLE IF NOT EXISTS public.guild_message_reads(guild_id uuid NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,player_id uuid NOT NULL REFERENCES public.profiles(id),last_read_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(guild_id,player_id));
CREATE TABLE IF NOT EXISTS public.guild_announcements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,author_id uuid NOT NULL REFERENCES public.profiles(id),body text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.guild_activity_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,event_type text NOT NULL,actor_id uuid,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.guild_reports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid REFERENCES public.guilds(id),reporter_id uuid NOT NULL REFERENCES public.profiles(id),category text NOT NULL,description text,status text NOT NULL DEFAULT 'open',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.guild_audit_log(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid,actor_id uuid,target_id uuid,action_type text NOT NULL,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.guild_analytics_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid,player_id uuid,event_type text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.guilds ENABLE ROW LEVEL SECURITY; ALTER TABLE public.guild_members ENABLE ROW LEVEL SECURITY; ALTER TABLE public.guild_invitations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.guild_join_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE public.guild_chat_messages ENABLE ROW LEVEL SECURITY; ALTER TABLE public.guild_message_reads ENABLE ROW LEVEL SECURITY; ALTER TABLE public.guild_announcements ENABLE ROW LEVEL SECURITY; ALTER TABLE public.guild_activity_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.guild_reports ENABLE ROW LEVEL SECURITY; ALTER TABLE public.guild_audit_log ENABLE ROW LEVEL SECURITY; ALTER TABLE public.guild_analytics_events ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.rt_active_guild_id(p_player uuid DEFAULT auth.uid()) RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT guild_id FROM public.guild_members WHERE player_id=p_player AND status='active' AND left_at IS NULL LIMIT 1 $$;
CREATE OR REPLACE FUNCTION public.rt_guild_can_manage(p_guild uuid,p_player uuid DEFAULT auth.uid()) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.guild_members WHERE guild_id=p_guild AND player_id=p_player AND status='active' AND role IN('leader','officer')) $$;
CREATE OR REPLACE FUNCTION public.create_guild(p_name text,p_tag text,p_description text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE uid uuid:=auth.uid(); gid uuid; n text:=lower(regexp_replace(trim(coalesce(p_name,'')),'\s+',' ','g')); t text:=upper(trim(coalesce(p_tag,''))); BEGIN IF uid IS NULL OR public.rt_social_restricted(uid) OR public.rt_active_guild_id(uid) IS NOT NULL OR NOT public.rt_check_rate_limit(uid,'guild_create',3,86400) THEN RAISE EXCEPTION 'guild creation unavailable'; END IF; IF n !~ '^[[:alnum:]][[:alnum:] ''_-]{1,30}[[:alnum:]]$' OR t !~ '^[A-Z0-9]{2,6}$' THEN RAISE EXCEPTION 'invalid guild name or tag'; END IF; INSERT INTO public.guilds(name,normalized_name,tag,leader_id,description) VALUES(trim(p_name),n,t,uid,nullif(left(trim(p_description),300),'')) RETURNING id INTO gid; INSERT INTO public.guild_members(guild_id,player_id,role) VALUES(gid,uid,'leader'); RETURN jsonb_build_object('ok',true,'guildId',gid); END $$;
CREATE OR REPLACE FUNCTION public.invite_to_guild(p_player uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE gid uuid:=public.rt_active_guild_id(); BEGIN IF gid IS NULL OR NOT public.rt_guild_can_manage(gid) OR public.rt_social_restricted(p_player) OR public.rt_is_blocked(auth.uid(),p_player) OR EXISTS(SELECT 1 FROM public.guild_members m WHERE m.guild_id=gid AND m.status='active' AND public.rt_is_blocked(m.player_id,p_player)) OR public.rt_active_guild_id(p_player) IS NOT NULL THEN RAISE EXCEPTION 'invite unavailable'; END IF; INSERT INTO public.guild_invitations(guild_id,sender_id,recipient_id) VALUES(gid,auth.uid(),p_player) ON CONFLICT(guild_id,recipient_id,status) DO UPDATE SET expires_at=now()+interval '24 hours'; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.respond_to_guild_invitation(p_invite uuid,p_accept boolean) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE i public.guild_invitations; BEGIN SELECT * INTO i FROM public.guild_invitations WHERE id=p_invite FOR UPDATE; IF i.recipient_id IS DISTINCT FROM auth.uid() OR i.status<>'pending' OR i.expires_at<=now() THEN RAISE EXCEPTION 'invitation unavailable'; END IF; IF NOT p_accept THEN UPDATE public.guild_invitations SET status='rejected' WHERE id=i.id; RETURN jsonb_build_object('ok',true); END IF; IF public.rt_active_guild_id(auth.uid()) IS NOT NULL OR (SELECT count(*) FROM public.guild_members WHERE guild_id=i.guild_id AND status='active') >= (SELECT max_members FROM public.guilds WHERE id=i.guild_id) OR EXISTS(SELECT 1 FROM public.guild_members m WHERE m.guild_id=i.guild_id AND m.status='active' AND public.rt_is_blocked(m.player_id,auth.uid())) THEN RAISE EXCEPTION 'cannot join guild'; END IF; INSERT INTO public.guild_members(guild_id,player_id) VALUES(i.guild_id,auth.uid()); UPDATE public.guild_invitations SET status='accepted' WHERE id=i.id; RETURN jsonb_build_object('ok',true,'guildId',i.guild_id); END $$;
CREATE OR REPLACE FUNCTION public.get_my_guild() RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT coalesce((SELECT jsonb_build_object('guild',to_jsonb(g),'members',(SELECT coalesce(jsonb_agg(to_jsonb(m)),'[]'::jsonb) FROM public.guild_members m WHERE m.guild_id=g.id AND m.status='active')) FROM public.guilds g WHERE g.id=public.rt_active_guild_id()),'null'::jsonb) $$;
CREATE OR REPLACE FUNCTION public.leave_guild() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE gid uuid:=public.rt_active_guild_id(); next_id uuid; BEGIN IF gid IS NULL THEN RAISE EXCEPTION 'not in guild'; END IF; SELECT player_id INTO next_id FROM public.guild_members WHERE guild_id=gid AND player_id<>auth.uid() AND status='active' ORDER BY CASE role WHEN 'officer' THEN 0 ELSE 1 END,joined_at LIMIT 1; UPDATE public.guild_members SET status='left',left_at=now() WHERE guild_id=gid AND player_id=auth.uid() AND status='active'; IF next_id IS NULL THEN UPDATE public.guilds SET status='disbanded',disbanded_at=now() WHERE id=gid; ELSE UPDATE public.guild_members SET role='leader' WHERE guild_id=gid AND player_id=next_id; UPDATE public.guilds SET leader_id=next_id WHERE id=gid; END IF; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.transfer_guild_ownership(p_player uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE gid uuid:=public.rt_active_guild_id(); BEGIN IF gid IS NULL OR NOT EXISTS(SELECT 1 FROM public.guild_members WHERE guild_id=gid AND player_id=auth.uid() AND role='leader' AND status='active') OR NOT EXISTS(SELECT 1 FROM public.guild_members WHERE guild_id=gid AND player_id=p_player AND status='active') THEN RAISE EXCEPTION 'transfer denied'; END IF; UPDATE public.guild_members SET role='officer' WHERE guild_id=gid AND player_id=auth.uid(); UPDATE public.guild_members SET role='leader' WHERE guild_id=gid AND player_id=p_player; UPDATE public.guilds SET leader_id=p_player WHERE id=gid; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.send_guild_chat_message(p_client_id text,p_body text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE gid uuid:=public.rt_active_guild_id(); s jsonb; BEGIN IF gid IS NULL OR public.rt_social_restricted(auth.uid()) OR nullif(trim(p_client_id),'') IS NULL OR NOT public.rt_check_rate_limit(auth.uid(),'guild_chat',60,60) THEN RAISE EXCEPTION 'chat unavailable'; END IF; s:=public.rt_safety_check_message(p_body); IF NOT coalesce((s->>'ok')::boolean,false) THEN RAISE EXCEPTION 'message rejected'; END IF; INSERT INTO public.guild_chat_messages(guild_id,sender_id,client_message_id,body,safe_body,status) VALUES(gid,auth.uid(),left(trim(p_client_id),128),s->>'safeBody',s->>'safeBody',CASE WHEN s->>'state'='held' THEN 'held' ELSE 'sent' END) ON CONFLICT(guild_id,sender_id,client_message_id) DO NOTHING; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.get_guild_chat_messages(p_limit integer DEFAULT 50) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE gid uuid:=public.rt_active_guild_id(); BEGIN IF gid IS NULL THEN RAISE EXCEPTION 'not in guild'; END IF; RETURN jsonb_build_object('messages',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.created_at) FROM (SELECT * FROM public.guild_chat_messages WHERE guild_id=gid AND status<>'deleted' ORDER BY created_at DESC LIMIT least(greatest(coalesce(p_limit,50),1),100)) x),'[]'::jsonb)); END $$;
CREATE OR REPLACE FUNCTION public.report_guild(p_guild uuid,p_category text,p_description text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.uid() IS NULL OR nullif(trim(p_category),'') IS NULL THEN RAISE EXCEPTION 'invalid report'; END IF; INSERT INTO public.guild_reports(guild_id,reporter_id,category,description) VALUES(p_guild,auth.uid(),left(trim(p_category),80),nullif(left(trim(p_description),1000),'')); RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.disband_guild() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE gid uuid:=public.rt_active_guild_id(); BEGIN IF gid IS NULL OR NOT EXISTS(SELECT 1 FROM public.guild_members WHERE guild_id=gid AND player_id=auth.uid() AND role='leader' AND status='active') THEN RAISE EXCEPTION 'leader required'; END IF; UPDATE public.guilds SET status='disbanded',disbanded_at=now() WHERE id=gid; UPDATE public.guild_members SET status='left',left_at=now() WHERE guild_id=gid AND status='active'; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.search_discoverable_guilds(p_query text DEFAULT '',p_limit integer DEFAULT 20) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT jsonb_build_object('guilds',coalesce((SELECT jsonb_agg(to_jsonb(g)) FROM (SELECT id,name,tag,description,max_members FROM public.guilds WHERE status='active' AND discoverable AND (trim(coalesce(p_query,''))='' OR normalized_name ILIKE '%'||lower(trim(p_query))||'%') ORDER BY created_at DESC LIMIT least(greatest(coalesce(p_limit,20),1),50)) g),'[]'::jsonb)) $$;
CREATE OR REPLACE FUNCTION public.reconcile_guild_ownership(p_guild uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE n uuid; BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF; IF NOT EXISTS(SELECT 1 FROM public.guild_members WHERE guild_id=p_guild AND role='leader' AND status='active') THEN SELECT player_id INTO n FROM public.guild_members WHERE guild_id=p_guild AND status='active' ORDER BY joined_at LIMIT 1; IF n IS NULL THEN UPDATE public.guilds SET status='disbanded',disbanded_at=now() WHERE id=p_guild; ELSE UPDATE public.guild_members SET role='leader' WHERE guild_id=p_guild AND player_id=n; UPDATE public.guilds SET leader_id=n WHERE id=p_guild; END IF; END IF; RETURN jsonb_build_object('ok',true); END $$;
CREATE OR REPLACE FUNCTION public.run_guild_maintenance() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE g uuid; BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF; UPDATE public.guild_invitations SET status='expired' WHERE status='pending' AND expires_at<=now(); FOR g IN SELECT id FROM public.guilds WHERE status='active' LOOP PERFORM public.reconcile_guild_ownership(g); END LOOP; RETURN jsonb_build_object('ok',true); END $$;

-- ============================================================================
-- 5 Analytics / Ops / Maintenance
-- ============================================================================
CREATE OR REPLACE FUNCTION public.run_phase10l_maintenance() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF; RETURN jsonb_build_object('worldEvents',public.run_world_event_maintenance(),'guilds',public.run_guild_maintenance()); END $$;
CREATE OR REPLACE FUNCTION public.get_phase10l_ops_dashboard() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NOT public.rt_is_social_operator('moderator') THEN RAISE EXCEPTION 'operator required'; END IF; RETURN jsonb_build_object('activeWorldEvents',(SELECT count(*) FROM public.world_event_instances WHERE status='active'),'openWorldEventAlerts',(SELECT count(*) FROM public.world_event_operational_alerts WHERE status='open'),'activeTournaments',(SELECT count(*) FROM public.tournament_instances WHERE status='active'),'openTournamentDisputes',(SELECT count(*) FROM public.tournament_disputes WHERE status='open'),'activeGuilds',(SELECT count(*) FROM public.guilds WHERE status='active'),'openGuildReports',(SELECT count(*) FROM public.guild_reports WHERE status='open')); END $$;

-- ============================================================================
-- 6 Seeds
-- ============================================================================
INSERT INTO public.character_cosmetic_definitions(id,name,slot,status) VALUES
 ('base_default','Default Base','base','active'),('hair_short','Short Hair','hair','active'),('hair_long','Long Hair','hair','active'),('outfit_starter_dark','Starter Dark Outfit','outfit','active'),('outfit_market_apron','Market Apron','outfit','active'),('hat_beanie','Beanie','hat','active'),('glasses_round','Round Glasses','glasses','active'),('cosmetic_test_event_pin','TEST Event Pin','badge','active'),('cosmetic_tournament_champion','Tournament Champion','badge','draft'),('cosmetic_guild_founder','Guild Founder','badge','draft') ON CONFLICT(id) DO NOTHING;
INSERT INTO public.world_event_definitions(id,name,description,status,is_test) VALUES ('test-town-tour-event','TEST Town Tour','Inactive TEST world event.','draft',true),('test-market-rush','TEST Market Rush','Inactive TEST world event.','draft',true),('test-community-milestone','TEST Community Milestone','Inactive TEST world event.','draft',true) ON CONFLICT(id) DO NOTHING;
INSERT INTO public.tournament_definitions(id,name,status,is_test,rules) VALUES ('test-explorer-score-challenge','TEST Explorer Score Challenge','draft',true,'{"trustedReceiptsOnly":true,"noSolSpl":true}'::jsonb) ON CONFLICT(id) DO NOTHING;

-- ============================================================================
-- 7 RLS notes / RPC grants
-- ============================================================================
COMMENT ON TABLE public.player_character_cosmetics IS 'Phase 10L ownership source of truth; browser cannot insert cosmetic grants.';
COMMENT ON TABLE public.world_event_reward_allocations IS 'Phase 10L server-created, in-game-only reward allocations.';
COMMENT ON TABLE public.guild_members IS 'Phase 10L membership is RPC-only; no client INSERT policy.';
REVOKE ALL ON FUNCTION public.rt_ensure_default_character_cosmetics(uuid),public.get_my_character_cosmetics(),public.get_my_character_loadout(),public.update_character_loadout(jsonb,text),public.get_public_character_loadout(uuid),public.grant_character_cosmetic(uuid,text,text),public.revoke_character_cosmetic(uuid,text,text),public.reconcile_character_loadout(uuid),public.transition_world_event_state(uuid,text),public.schedule_world_event(text,timestamptz,timestamptz),public.register_for_world_event(uuid),public.withdraw_from_world_event(uuid),public.get_my_world_event_registration(uuid),public.record_world_event_contribution(uuid,text,uuid,text,integer),public.evaluate_world_event_instance(uuid),public.get_active_world_events(),public.claim_world_event_reward(uuid),public.run_world_event_maintenance(),public.register_for_tournament(uuid),public.submit_tournament_score(uuid,uuid,integer),public.get_tournament_standings(uuid),public.finalize_tournament_results(uuid),public.file_tournament_dispute(uuid,text),public.claim_tournament_reward(uuid),public.rt_active_guild_id(uuid),public.rt_guild_can_manage(uuid,uuid),public.create_guild(text,text,text),public.invite_to_guild(uuid),public.respond_to_guild_invitation(uuid,boolean),public.get_my_guild(),public.leave_guild(),public.transfer_guild_ownership(uuid),public.send_guild_chat_message(text,text),public.get_guild_chat_messages(integer),public.report_guild(uuid,text,text),public.disband_guild(),public.search_discoverable_guilds(text,integer),public.reconcile_guild_ownership(uuid),public.run_guild_maintenance(),public.run_phase10l_maintenance(),public.get_phase10l_ops_dashboard() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_my_character_cosmetics(),public.get_my_character_loadout(),public.update_character_loadout(jsonb,text),public.get_public_character_loadout(uuid),public.reconcile_character_loadout(uuid),public.register_for_world_event(uuid),public.withdraw_from_world_event(uuid),public.get_my_world_event_registration(uuid),public.record_world_event_contribution(uuid,text,uuid,text,integer),public.get_active_world_events(),public.claim_world_event_reward(uuid),public.register_for_tournament(uuid),public.submit_tournament_score(uuid,uuid,integer),public.get_tournament_standings(uuid),public.file_tournament_dispute(uuid,text),public.claim_tournament_reward(uuid),public.create_guild(text,text,text),public.invite_to_guild(uuid),public.respond_to_guild_invitation(uuid,boolean),public.get_my_guild(),public.leave_guild(),public.transfer_guild_ownership(uuid),public.send_guild_chat_message(text,text),public.get_guild_chat_messages(integer),public.report_guild(uuid,text,text),public.disband_guild(),public.search_discoverable_guilds(text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_character_cosmetic(uuid,text,text),public.revoke_character_cosmetic(uuid,text,text),public.transition_world_event_state(uuid,text),public.schedule_world_event(text,timestamptz,timestamptz),public.evaluate_world_event_instance(uuid),public.run_world_event_maintenance(),public.finalize_tournament_results(uuid),public.reconcile_guild_ownership(uuid),public.run_guild_maintenance(),public.run_phase10l_maintenance(),public.get_phase10l_ops_dashboard() TO authenticated;
COMMIT;
